export interface ObjectionEntry {
  id: string;
  category: string;    // human-readable category for the form's grouping
  trigger: string;     // short label — what the seller said
  response: string;    // verbatim agent talking point
  isDefaultSelected?: boolean; // Refinement #14 — pre-checked on form load
}

export const OBJECTION_LIBRARY: ObjectionEntry[] = [
  {
    id: 'zillow-says-higher',
    category: 'Valuation pushback',
    trigger: '"Zillow says my home is worth more"',
    response:
      "Zestimates are generated by an algorithm that can't see inside your home or know your local market the way an active agent does. They have a published margin of error that can run several percent in either direction. Let me show you what comparable homes actually sold for recently — those are the numbers buyers and appraisers will reference.",
    isDefaultSelected: true,
  },
  {
    id: 'test-higher-price',
    category: 'Valuation pushback',
    trigger: '"We want to test the market at a higher price"',
    response:
      "I understand the appeal. Here's what tends to happen: properties priced meaningfully above comparable sales stay on the market materially longer, and the longer they sit, the more buyers wonder what's wrong with them. The first two weeks are when you get the most attention. Let's price to compete in that window — we can always reassess.",
  },
  {
    id: 'neighbor-sold-for-X',
    category: 'Valuation pushback',
    trigger: '"My neighbor sold for $X — mine should be the same"',
    response:
      "Neighbor comps are useful but every home has differences — square footage, updates, condition, lot, view, the buyer who happened to be looking that week. Here's the comp set adjusted for your specific home. The math gets more precise when we account for those differences.",
  },
  {
    id: 'home-is-special',
    category: 'Valuation pushback',
    trigger: '"My home is special / unique"',
    response:
      "Every home has features the seller loves — that's part of what makes selling emotional. The challenge is that buyers may not value those features the same way until they see the home. My job is to highlight what the right buyer will care about most. Let's walk through what makes your home stand out and how we'd lead with that in the marketing.",
  },
  {
    id: 'whats-your-commission',
    category: 'Commission conversation',
    trigger: '"What\'s your commission?"',
    response:
      "Let's talk about what you're getting for that commission first. The agents who invest meaningfully in marketing — professional photography, dedicated social campaigns, syndication beyond the MLS, follow-up systems — typically get sellers a higher net even after the commission. I'd rather show you what I'd do for your specific home and then walk through the rate, so you can judge whether the value matches the cost.",
    isDefaultSelected: true,
  },
  {
    id: 'can-you-do-less',
    category: 'Commission conversation',
    trigger: '"Can you do it for less?"',
    response:
      "I understand the question — it's a meaningful number, and I want to be straightforward. My services include the marketing investment, the negotiation work, the day-to-day coordination, and standing behind you when things get complicated. If I lower the rate, I'd have to reduce what I can put into selling your home. What I can do is walk you through exactly what's included so you can decide if the value matches. If it doesn't, you should hire someone whose offering does match what you need.",
  },
  {
    id: 'why-you-vs-other-agent',
    category: 'Agent selection',
    trigger: '"Why should I list with you instead of another agent?"',
    response:
      "That's the right question to ask. The honest answer is that you should hire whoever you trust to handle your largest financial asset. What I can offer is transparency — here's my track record, here's exactly what I'll do for your home, and here's how I'll communicate throughout. Take that to the other agents and ask them the same questions. If my plan is the strongest, I'd love to represent you.",
    isDefaultSelected: true,
  },
  {
    id: 'interview-other-agents',
    category: 'Agent selection',
    trigger: '"We want to interview a few agents"',
    response:
      "Of course. Here's what I'd ask each one: what their marketing plan looks like in writing, how many homes they've sold in this neighborhood, their average sale-to-list ratio, and what their plan is if your home hasn't sold in 21 days. I'm confident in my answers. Take your time, and when you're ready, I'd be honored to represent you.",
  },
  {
    id: 'not-in-a-rush',
    category: 'Timing / urgency',
    trigger: '"We\'re not in a rush"',
    response:
      "That's an advantage if we use it right. We can price slightly under market to drive multiple offers, then choose the best one — financial strength, contingencies, closing timeline. The buyer who waits longer in this market is the buyer who pays. Timing the launch and pricing strategy intentionally tends to net more than waiting passively.",
  },
  {
    id: 'wait-for-better-market',
    category: 'Timing / urgency',
    trigger: '"Maybe we should wait for a better market"',
    response:
      "I understand that instinct. Here's the honest read: market timing is hard to predict, and waiting often costs more than people expect — property taxes, maintenance, interest if you have a loan, and the opportunity cost of capital tied up in the home. If your reasons for selling are still true a year from now, the math usually favors selling sooner. Let's talk about what changed for you and what the right timing actually is.",
  },
  {
    id: 'we-can-sell-ourselves',
    category: 'FSBO / alternatives',
    trigger: '"We can sell it ourselves"',
    response:
      "FSBO is a real option, and some sellers do it well. Here's what tends to happen: most FSBOs spend significant time fielding calls from agents and price negotiators, and the data shows FSBO homes typically sell for materially less than agent-listed homes. I'd love to show you what my marketing reach would add. If at the end you still want to try FSBO, I'll respect that — but at least you'd have the comparison.",
  },
  {
    id: 'what-about-ibuyer-opendoor',
    category: 'FSBO / alternatives',
    trigger: '"What about Opendoor or an iBuyer?"',
    response:
      "iBuyers like Opendoor make sense for sellers who prioritize speed and convenience over price. The tradeoff is significant — typical iBuyer offers come in noticeably below market value, plus service fees that often add another several percent. That's tens of thousands of dollars left on the table for the convenience. If you genuinely need speed, I can help you compare an iBuyer offer side by side with what my marketing would deliver. Then you decide which trade you'd rather make.",
    isDefaultSelected: true,
  },
  {
    id: 'dual-agency-conflict',
    category: 'Agent representation',
    trigger: '"What if the buyer is also yours?"',
    response:
      "Great question. Dual agency creates a real conflict — I'd be representing both sides. My approach is to make sure each side has independent representation. If a buyer comes directly to me about your listing, I'd refer them to another agent so they have someone advocating purely for them. That keeps your interests protected, and the deal cleaner.",
  },
  {
    id: 'why-hasnt-it-sold',
    category: 'Relisting / price reduction',
    trigger: '"Why hasn\'t it sold yet?" (relisting / current listing)',
    response:
      "This is the conversation I'd rather have before we relist. The honest data: if a home doesn't get strong activity in the first 21 days, the most common reasons are price, presentation, or marketing reach. Let's look at what showings and feedback we got, what comparable homes sold for in that window, and decide whether the adjustment is price, photography, staging, or all three. Doing nothing and waiting is usually the most expensive option.",
  },
  {
    id: 'pre-listing-investments',
    category: 'Pre-listing prep',
    trigger: '"Should I make repairs / stage / paint before listing?"',
    response:
      "This depends on the home and the buyer pool we're targeting. Generally: cleaning, decluttering, and small touch-ups always pay back. Paint and staging often pay back at two to five times the cost in faster sale and higher price. Bigger renovations rarely pay back enough to justify them right before listing — buyers want to make their own choices. Let me walk through the specific spots I'd recommend and what each would change.",
  },
];

/**
 * IDs of objections pre-selected when an agent opens a fresh SIR form.
 * Refinement #14: reduce decision fatigue with sensible universal defaults.
 * Agent unchecks any they don't want, checks any additional ones.
 */
export const DEFAULT_SELECTED_OBJECTION_IDS: readonly string[] = OBJECTION_LIBRARY
  .filter((entry) => entry.isDefaultSelected)
  .map((entry) => entry.id);

export function getObjectionById(id: string): ObjectionEntry | undefined {
  return OBJECTION_LIBRARY.find((entry) => entry.id === id);
}
